"""Constants for the salary prediction model."""

MODEL_FILENAME = "salary_model.pkl"
RESOURCES_DIR_NAME = "resources"

DEFAULT_N_ESTIMATORS = 200
DEFAULT_MAX_DEPTH = 6
DEFAULT_LEARNING_RATE = 0.05
DEFAULT_TEST_SIZE = 0.2
DEFAULT_RANDOM_STATE = 42
SALARY_MIN = 5_000
SALARY_MAX = 500_000
